Fix setup.py error with unsupported python version
The format string was not correct so the RuntimeError wasn't raised properly

Error was:

  TypeError: not all arguments converted during string formatting